### ISSUE TITLE
请求引用

### ISSUE THREAD

**Issue by drinktoomuchsax** [HuaYuXiao/Music-player-APP-in-Android-Studio#1]
hallo，请求在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及引用你的仓库内容：)

**Comment by HuaYuXiao** [comment]
可以，不过我这边好多文件都找不到了，建议你参考CSDN或GitHub上的其他项目😊。

**Comment by drinktoomuchsax** [comment]
好的，向你敬礼👍🏻
